[BRE-101] Remove dept-devops from CODEOWNERS
bitwarden/sm-action pull request #122
Opened 2024-06-10 13:32 UTC by michalchecinski

https://bitwarden.atlassian.net/browse/BRE-101 Remove `dept-devops` from CODEOWNERS and add `bitwarden/dept-bre` for `.github/workflows/release.yml` wofklow.

2024-06-20 14:15 UTC, coltonhurst submitted a review, later dismissed

2024-10-16 18:14 UTC, vgrassia requested changes

2024-10-16 18:14 UTC, vgrassia commented on .github/CODEOWNERS
> +.github/workflows/build-test.yml @bitwarden/dept-bre @bitwarden/team-secrets-manager-dev
```suggestion
.github/workflows/build-test.yml @bitwarden/dept-bre @bitwarden/team-secrets-manager-dev
.github/workflows/release.yml @bitwarden/dept-bre @bitwarden/team-secrets-manager-dev
```

2024-10-17 14:16 UTC, vgrassia approved these changes

2024-10-17 14:19 UTC, coltonhurst approved these changes

2024-10-17 14:19 UTC, merged